// Inicializar Supabase
const SUPABASE_URL = "https://gecfzunnxcjsuzoceshc.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlY2Z6dW5ueGNqc3V6b2Nlc2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2OTE4MjgsImV4cCI6MjA5MDI2NzgyOH0.dVxnQFpo8nXRAEuETLA7atGkxmAfMH0DUgbvvUCTYJc";

window.supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);